### ISSUE TITLE
Large config files are slow to import and populate the System Explorer tree

### ISSUE THREAD

**Issue by jkreienh** [ni/niveristand-ballard-arinc429-custom-device#212]
**Describe the bug**
The current version of the custom device takes much longer than legacy versions of the custom device to load and populate the System Explorer tree when large HW and Parameter files are used.

**To Reproduce**
1. Update attached HW and Parameter File extensions from txt to xml
[POC_8Tx_to_8Rx_Full_Bus_Load_HW_Core_0.txt](https://github.com/ni/niveristand-ballard-arinc429-custom-device/files/8535184/POC_8Tx_to_8Rx_Full_Bus_Load_HW_Core_0.txt)
[POC_8Tx_to_8Rx_Full_Bus_Load_PARAM_Core_0.txt](https://github.com/ni/niveristand-ballard-arinc429-custom-device/files/8535187/POC_8Tx_to_8Rx_Full_Bus_Load_PARAM_Core_0.txt)

2. Load the attached HW file
3. Load the attached Parameter File
4. Observe a load time of ~10 minutes

**Expected behavior**
Typical load times (legacy custom device) would be under 30 seconds for comparable files with ~2300 parameters

 - OS: Linx64
 - Version: 21.0.0.19

**Comment by buckd** [comment]
Almost all of the time spent during this import is due to creating items in the System Explorer tree without buffering them. The parsing of the parameters file takes about 3.5 seconds. After parsing, creating the desired items in the system definition (outside of the System Explorer UI) takes about 14 seconds, so a total of around 18 seconds on my test machine.

When performing the import inside System Explorer with buffering enabled, the total time is about 30 seconds. So, almost 40 percent of the total time is still redrawing everything in the System Explorer tree. We can't really do much else for the redraw, but buffering should get close to the previous performance.

Note that the legacy custom device does have buffering around the tree creation, which is why it is so much faster than the current implementation in this custom device.
